name: Order Service CI

on:
  push:
    paths:
      - 'order-service/**'
  pull_request:
    paths:
      - 'order-service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: order-service

      - name: Run tests
        run: npm test
        working-directory: order-service
